title: SHAO Zhijing (Neil)'s personal website
logo: /assets/img/DSC06114-2.jpg
description: We can only observe the high dimensional world from our low dimensional projection.
show_downloads: false
google_analytics: G-SRNMM4RT7F
theme: jekyll-theme-minimal
